"use client";

/**
 * Workspace Admin Page
 * 
 * Route: /admin/workspaces
 * Platform admin configuration page for workspace module.
 * 
 * This file is auto-generated by create-cora-project.sh when module-ws is included.
 */

import { PlatformAdminConfigPage } from "@{{PROJECT_NAME}}/module-ws";

export default function WorkspaceAdminPage() {
  return <PlatformAdminConfigPage />;
}
