import { handlers } from "@/auth";

/**
 * NextAuth.js v5 API Route Handler
 *
 * This route handles all authentication requests:
 * - GET /api/auth/signin - Sign in page
 * - POST /api/auth/signin/okta - Initiate Okta OAuth flow
 * - GET /api/auth/callback/okta - OAuth callback from Okta
 * - POST /api/auth/signout - Sign out
 * - GET /api/auth/session - Get current session
 * - GET /api/auth/csrf - Get CSRF token
 *
 * The handlers are generated by NextAuth based on the configuration
 * in /auth.ts. No additional logic is needed here.
 *
 * @see https://authjs.dev/getting-started/migrating-to-v5
 */
export const { GET, POST } = handlers;
