#!/bin/bash

# Run Database Migrations
# Standalone script to consolidate and execute database schema files
# Useful for testing idempotency and debugging schema issues
#
# Usage: ./run-database-migrations.sh <stack-directory>

set -e

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# --- Parse Arguments ---
STACK_DIR="$1"

if [[ -z "$STACK_DIR" ]]; then
  echo "Usage: $0 <stack-directory>"
  echo ""
  echo "Example:"
  echo "  $0 ~/code/sts/test13/ai-sec-stack"
  echo ""
  echo "This script will:"
  echo "  1. Find all schema files in packages/*/db/schema/*.sql"
  echo "  2. Consolidate them into scripts/setup-database.sql"
  echo "  3. Execute against the database (requires .env with DB credentials)"
  exit 1
fi

# Validate stack directory exists
if [[ ! -d "$STACK_DIR" ]]; then
  log_error "Stack directory not found: $STACK_DIR"
  exit 1
fi

# Check for packages directory
if [[ ! -d "$STACK_DIR/packages" ]]; then
  log_error "Packages directory not found: $STACK_DIR/packages"
  exit 1
fi

echo "========================================"
echo "  CORA Database Migration Runner"
echo "========================================"
echo ""
log_info "Stack Directory: $STACK_DIR"
echo ""

# --- Consolidate Database Schemas ---
consolidate_database_schemas() {
  local stack_dir="$1"
  
  log_step "Consolidating database schemas from all modules..."
  
  # Create scripts directory if it doesn't exist
  mkdir -p "${stack_dir}/scripts"
  
  # Find all schema files from modules
  local schema_files=()
  while IFS= read -r schema_file; do
    [[ -n "$schema_file" ]] && schema_files+=("$schema_file")
  done < <(find "${stack_dir}/packages" -path "*/db/schema/*.sql" -type f 2>/dev/null | sort)
  
  if [[ ${#schema_files[@]} -eq 0 ]]; then
    log_warn "No database schema files found in modules"
    log_info "Checked: ${stack_dir}/packages/*/db/schema/*.sql"
    exit 1
  fi
  
  log_info "Found ${#schema_files[@]} schema files"
  echo ""
  
  # Create consolidated setup-database.sql
  cat > "${stack_dir}/scripts/setup-database.sql" << 'SQLHEADER'
-- =============================================================================
-- CORA Database Setup Script
-- =============================================================================
-- This file consolidates all database schemas from CORA modules.
-- It is idempotent and safe to run multiple times.
--
-- Generated by: run-database-migrations.sh
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

SQLHEADER
  
  # Append each schema file
  for schema_file in "${schema_files[@]}"; do
    local module_name=$(basename "$(dirname "$(dirname "$(dirname "$schema_file")")")")
    local schema_name=$(basename "$schema_file")
    
    echo "" >> "${stack_dir}/scripts/setup-database.sql"
    echo "-- =============================================================================" >> "${stack_dir}/scripts/setup-database.sql"
    echo "-- Module: ${module_name}" >> "${stack_dir}/scripts/setup-database.sql"
    echo "-- Schema: ${schema_name}" >> "${stack_dir}/scripts/setup-database.sql"
    echo "-- =============================================================================" >> "${stack_dir}/scripts/setup-database.sql"
    echo "" >> "${stack_dir}/scripts/setup-database.sql"
    
    cat "$schema_file" >> "${stack_dir}/scripts/setup-database.sql"
    
    log_info "  ✓ Added ${module_name}/${schema_name}"
  done
  
  echo ""
  log_info "Created consolidated ${stack_dir}/scripts/setup-database.sql"
}

# --- Run Database Migrations ---
run_migrations() {
  local stack_dir="$1"
  
  log_step "Running database migrations..."
  echo ""
  
  # Check if database credentials are available
  if [[ ! -f "${stack_dir}/scripts/validation/.env" ]]; then
    log_error "Database credentials not found at ${stack_dir}/scripts/validation/.env"
    echo ""
    log_info "Create a .env file with database credentials:"
    echo "  SUPABASE_DB_HOST=your-host"
    echo "  SUPABASE_DB_PORT=6543"
    echo "  SUPABASE_DB_NAME=postgres"
    echo "  SUPABASE_DB_USER=your-user"
    echo "  SUPABASE_DB_PASSWORD=your-password"
    exit 1
  fi
  
  # Load database credentials
  source "${stack_dir}/scripts/validation/.env"
  
  # Verify required credentials are set
  if [[ -z "$SUPABASE_DB_HOST" ]] || [[ -z "$SUPABASE_DB_USER" ]] || [[ -z "$SUPABASE_DB_PASSWORD" ]]; then
    log_error "Database credentials incomplete in ${stack_dir}/scripts/validation/.env"
    echo ""
    log_info "Required environment variables:"
    echo "  SUPABASE_DB_HOST"
    echo "  SUPABASE_DB_USER"
    echo "  SUPABASE_DB_PASSWORD"
    exit 1
  fi
  
  # Check if psql is available
  if ! command -v psql &> /dev/null; then
    log_error "psql not found. Install PostgreSQL client:"
    echo "  On macOS: brew install postgresql"
    echo "  On Ubuntu: sudo apt-get install postgresql-client"
    exit 1
  fi
  
  # URL-encode password for PostgreSQL connection string
  url_encode_password() {
    python3 -c "import urllib.parse; print(urllib.parse.quote('$1', safe=''))"
  }
  
  # Build connection string with URL-encoded password
  local encoded_password=$(url_encode_password "$SUPABASE_DB_PASSWORD")
  local conn_string="postgresql://${SUPABASE_DB_USER}:${encoded_password}@${SUPABASE_DB_HOST}:${SUPABASE_DB_PORT:-6543}/${SUPABASE_DB_NAME:-postgres}"
  
  # Test connection
  log_info "Testing database connection..."
  if ! psql "$conn_string" -c "SELECT 1;" > /dev/null 2>&1; then
    log_error "Failed to connect to database"
    echo ""
    log_info "Connection details:"
    echo "  Host: $SUPABASE_DB_HOST"
    echo "  Port: ${SUPABASE_DB_PORT:-6543}"
    echo "  Database: ${SUPABASE_DB_NAME:-postgres}"
    echo "  User: $SUPABASE_DB_USER"
    exit 1
  fi
  log_info "✓ Database connection successful"
  echo ""
  
  # Execute setup-database.sql with detailed output
  if [[ -f "${stack_dir}/scripts/setup-database.sql" ]]; then
    log_step "Executing setup-database.sql..."
    echo ""
    echo "  ========================================="
    echo "  Database Schema Creation - Detailed Log"
    echo "  ========================================="
    echo ""
    
    # Create temporary files to capture psql output
    local psql_output=$(mktemp)
    local psql_errors=$(mktemp)
    
    # Execute WITHOUT ON_ERROR_STOP to allow idempotent re-runs
    # (Some schema files don't use IF NOT EXISTS)
    psql "$conn_string" -f "${stack_dir}/scripts/setup-database.sql" \
         --echo-errors \
         > "$psql_output" 2> "$psql_errors"
    
    local psql_exit_code=$?
    
    # Check for FATAL errors (not just "already exists" warnings)
    if grep -qE "FATAL|ERROR:.*does not exist|ERROR:.*permission denied|ERROR:.*syntax error" "$psql_errors" && \
       ! grep -qE "ERROR:.*already exists" "$psql_errors"; then
      # Fatal error occurred
      true  # Will be handled in error block below
    elif [[ $psql_exit_code -eq 0 ]] || grep -qE "ERROR:.*already exists" "$psql_errors"; then
      
      # Show summary of what was executed
      log_info "Schema execution completed. Summary:"
      echo ""
      
      # Count and show created objects
      local tables_created=$(grep -c "CREATE TABLE" "$psql_output" 2>/dev/null || echo "0")
      local indexes_created=$(grep -c "CREATE INDEX" "$psql_output" 2>/dev/null || echo "0")
      local functions_created=$(grep -c "CREATE FUNCTION\|CREATE OR REPLACE FUNCTION" "$psql_output" 2>/dev/null || echo "0")
      local policies_created=$(grep -c "CREATE POLICY" "$psql_output" 2>/dev/null || echo "0")
      local inserts_done=$(grep -c "INSERT INTO" "$psql_output" 2>/dev/null || echo "0")
      
      echo "  📊 Objects Created/Updated:"
      echo "     - Tables: $tables_created"
      echo "     - Indexes: $indexes_created"
      echo "     - Functions: $functions_created"
      echo "     - Policies: $policies_created"
      echo "     - Data Inserts: $inserts_done"
      echo ""
      
      # Check for any warnings or notices in output
      if grep -q "NOTICE\|WARNING" "$psql_output" 2>/dev/null; then
        log_warn "Notices/Warnings detected:"
        grep "NOTICE\|WARNING" "$psql_output" | sed 's/^/     /'
        echo ""
      fi
      
      # Show any skipped operations (objects that already exist)
      local skipped=$(grep -c "already exists, skipping" "$psql_output" 2>/dev/null || echo "0")
      if [[ $skipped -gt 0 ]]; then
        log_info "Skipped $skipped objects that already exist (idempotency check passed)"
        echo ""
      fi
      
      log_info "✅ Database schema applied successfully!"
      echo ""
      log_info "💡 Script is idempotent - safe to run multiple times"
    else
      log_error "❌ Failed to execute setup-database.sql"
      echo ""
      log_error "PostgreSQL Errors:"
      cat "$psql_errors" | sed 's/^/     /'
      echo ""
      
      # Provide helpful diagnostics
      if grep -q "does not exist" "$psql_errors"; then
        log_warn "💡 Possible causes:"
        echo "     - Table referenced in policy/constraint doesn't exist yet"
        echo "     - Schema files may be in wrong order"
        echo "     - Check for typos in table names (e.g., 'profiles' vs 'user_profiles')"
        echo ""
      fi
      
      if grep -q "already exists" "$psql_errors"; then
      log_info "💡 Some objects already exist (this is expected for idempotent scripts)"
      log_info "   Consider updating schema files to use CREATE TABLE IF NOT EXISTS"
      echo ""
      fi
      
      log_info "To see full output, run manually:"
      echo "  psql \"$conn_string\" -f ${stack_dir}/scripts/setup-database.sql --echo-all"
      echo ""
      
      rm -f "$psql_output" "$psql_errors"
      exit 1
    fi
    
    # Cleanup temp files
    rm -f "$psql_output" "$psql_errors"
  else
    log_error "setup-database.sql not found at ${stack_dir}/scripts/setup-database.sql"
    exit 1
  fi
}

# --- Main Execution ---
consolidate_database_schemas "$STACK_DIR"
echo ""
run_migrations "$STACK_DIR"
echo ""

echo "========================================"
echo "  Migration Complete"
echo "========================================"
echo ""
log_info "Next steps:"
echo "  1. Verify database schema in Supabase Dashboard"
echo "  2. Run this script again to test idempotency"
echo "  3. Check that no duplicate records were created"
echo ""
