-- =============================================
-- MODULE-ACCESS: User Profiles (Production Schema)
-- =============================================
-- Purpose: Store user profile information
-- Source: Extracted from pm-app-stack production database Dec 2025
-- Note: id is BIGINT (not UUID) to match production

-- =============================================
-- PROFILES TABLE
-- =============================================

CREATE TABLE public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    avatar_url TEXT,
    avatar BYTEA,
    current_org_id UUID,
    global_role TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- =============================================
-- INDEXES
-- =============================================

CREATE INDEX idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX idx_profiles_email ON public.profiles(email);
CREATE INDEX idx_profiles_global_role ON public.profiles(global_role);
CREATE INDEX idx_profiles_current_org_id ON public.profiles(current_org_id);

-- =============================================
-- COMMENTS
-- =============================================

COMMENT ON TABLE public.profiles IS 'User profile information, one per auth.users record';
COMMENT ON COLUMN public.profiles.id IS 'Auto-incrementing BIGINT primary key';
COMMENT ON COLUMN public.profiles.user_id IS 'Foreign key to auth.users.id (one-to-one relationship)';
COMMENT ON COLUMN public.profiles.email IS 'User email (duplicated from auth.users for convenience)';
COMMENT ON COLUMN public.profiles.full_name IS 'Full name of user';
COMMENT ON COLUMN public.profiles.current_org_id IS 'Persists the user''s currently selected organization across sessions';
COMMENT ON COLUMN public.profiles.global_role IS 'Global role: global_user, global_admin, global_owner, super_admin';
COMMENT ON COLUMN public.profiles.avatar_url IS 'URL to avatar image (external storage)';
COMMENT ON COLUMN public.profiles.avatar IS 'Binary storage for avatar image';
COMMENT ON COLUMN public.profiles.metadata IS 'Flexible JSONB storage for additional profile attributes';

-- =============================================
-- FOREIGN KEYS (Added after orgs table exists)
-- =============================================

ALTER TABLE public.profiles 
ADD CONSTRAINT profiles_current_org_id_fkey 
FOREIGN KEY (current_org_id) REFERENCES public.orgs(id) ON DELETE SET NULL;

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Users can view their own profile
CREATE POLICY "Users can view own profile" 
    ON public.profiles
    FOR SELECT 
    TO authenticated
    USING (user_id = auth.uid());

-- Users can update their own profile
CREATE POLICY "Users can update own profile" 
    ON public.profiles
    FOR UPDATE 
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- Users can insert their own profile (during registration)
CREATE POLICY "Users can create own profile" 
    ON public.profiles
    FOR INSERT 
    TO authenticated
    WITH CHECK (user_id = auth.uid());

-- Service role has full access (for Lambda functions)
CREATE POLICY "Service role full access to profiles" 
    ON public.profiles
    FOR ALL
    USING (current_setting('request.jwt.claims', true)::json->>'role' = 'service_role');

-- =============================================
-- TRIGGER: Auto-update updated_at
-- =============================================

CREATE OR REPLACE FUNCTION update_profiles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_profiles_updated_at();
