-- =============================================
-- MODULE-ACCESS: User Profiles (Production Schema)
-- =============================================
-- Purpose: Store user profile information
-- Source: Extracted from pm-app-stack production database Dec 2025
-- Note: id is BIGINT (not UUID) to match production
-- Idempotent: Safe to run multiple times without errors

-- =============================================
-- PROFILES TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    avatar_url TEXT,
    avatar BYTEA,
    current_org_id UUID,
    global_role TEXT,
    created_by UUID,
    updated_by UUID,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- =============================================
-- INDEXES
-- =============================================

CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON public.profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_global_role ON public.profiles(global_role);
CREATE INDEX IF NOT EXISTS idx_profiles_current_org_id ON public.profiles(current_org_id);
CREATE INDEX IF NOT EXISTS idx_profiles_created_by ON public.profiles(created_by);
CREATE INDEX IF NOT EXISTS idx_profiles_updated_by ON public.profiles(updated_by);

-- =============================================
-- COMMENTS
-- =============================================

COMMENT ON TABLE public.profiles IS 'User profile information, one per auth.users record';
COMMENT ON COLUMN public.profiles.id IS 'Auto-incrementing BIGINT primary key';
COMMENT ON COLUMN public.profiles.user_id IS 'Foreign key to auth.users.id (one-to-one relationship)';
COMMENT ON COLUMN public.profiles.email IS 'User email (duplicated from auth.users for convenience)';
COMMENT ON COLUMN public.profiles.full_name IS 'Full name of user';
COMMENT ON COLUMN public.profiles.current_org_id IS 'Persists the user''s currently selected organization across sessions';
COMMENT ON COLUMN public.profiles.global_role IS 'Global role: global_user, global_admin, global_owner, super_admin';
COMMENT ON COLUMN public.profiles.avatar_url IS 'URL to avatar image (external storage)';
COMMENT ON COLUMN public.profiles.avatar IS 'Binary storage for avatar image';
COMMENT ON COLUMN public.profiles.created_by IS 'User who created this profile (usually same as user_id for self-created)';
COMMENT ON COLUMN public.profiles.updated_by IS 'User who last updated this profile';
COMMENT ON COLUMN public.profiles.metadata IS 'Flexible JSONB storage for additional profile attributes';

-- =============================================
-- FOREIGN KEYS (Idempotent - only add if not exists)
-- =============================================

-- Add foreign key constraint for current_org_id (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'profiles_current_org_id_fkey'
    ) THEN
        ALTER TABLE public.profiles 
        ADD CONSTRAINT profiles_current_org_id_fkey 
        FOREIGN KEY (current_org_id) REFERENCES public.orgs(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Add foreign key constraint for created_by (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'profiles_created_by_fkey'
    ) THEN
        ALTER TABLE public.profiles 
        ADD CONSTRAINT profiles_created_by_fkey 
        FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- Add foreign key constraint for updated_by (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'profiles_updated_by_fkey'
    ) THEN
        ALTER TABLE public.profiles 
        ADD CONSTRAINT profiles_updated_by_fkey 
        FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Drop existing policies (idempotent)
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can create own profile" ON public.profiles;
DROP POLICY IF EXISTS "Service role full access to profiles" ON public.profiles;

-- Recreate policies (now idempotent)
CREATE POLICY "Users can view own profile" 
    ON public.profiles
    FOR SELECT 
    TO authenticated
    USING (user_id = auth.uid());

CREATE POLICY "Users can update own profile" 
    ON public.profiles
    FOR UPDATE 
    TO authenticated
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can create own profile" 
    ON public.profiles
    FOR INSERT 
    TO authenticated
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Service role full access to profiles" 
    ON public.profiles
    FOR ALL
    USING (current_setting('request.jwt.claims', true)::json->>'role' = 'service_role');

-- =============================================
-- TRIGGER: Auto-update updated_at (Idempotent)
-- =============================================

-- Create function (idempotent with CREATE OR REPLACE)
CREATE OR REPLACE FUNCTION update_profiles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop and recreate trigger (idempotent)
DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_profiles_updated_at();
