"use client";

/**
 * Workspaces Page
 * 
 * Route: /ws
 * Renders the workspace list page from module-ws.
 * 
 * This file is auto-generated by create-cora-project.sh when module-ws is included.
 */

import { WorkspaceListPage } from "@{{PROJECT_NAME}}/module-ws";

export default function WorkspacesPage() {
  return <WorkspaceListPage />;
}
