#!/bin/bash

# Update Environment Files from Terraform Outputs
# 
# This script extracts API Gateway outputs from Terraform and updates
# the validation .env file in the stack repository.
#
# Usage: ./update-env-from-terraform.sh [ENV]
#
# Should be run after `deploy-terraform.sh` completes successfully.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV="${1:-dev}"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Extract project name from project.json
PROJECT_NAME=$(jq -r '.name' "${INFRA_ROOT}/project.json" 2>/dev/null || echo "")
if [[ -z "$PROJECT_NAME" ]]; then
  log_error "Could not determine project name from project.json"
  exit 1
fi

STACK_DIR="${INFRA_ROOT}/../${PROJECT_NAME}-stack"
VALIDATION_ENV="${STACK_DIR}/scripts/validation/.env"
CONFIG_FILE="${STACK_DIR}/setup.config.${PROJECT_NAME}.yaml"

log_step "Extracting Terraform outputs for ${PROJECT_NAME} (${ENV})..."

# Change to the environment directory
cd "${INFRA_ROOT}/envs/${ENV}"

# Check if Terraform is initialized
if [[ ! -d ".terraform" ]]; then
  log_error "Terraform not initialized. Run 'terraform init' first."
  exit 1
fi

# Load AWS credentials from infra .env (must be sourced before terraform commands)
if [[ -f "${INFRA_ROOT}/.env" ]]; then
  log_info "Loading AWS credentials from ${INFRA_ROOT}/.env..."
  set -a  # automatically export all variables
  source "${INFRA_ROOT}/.env"
  set +a
  log_info "Using AWS profile: ${AWS_PROFILE:-default}"
else
  log_warn "No .env file found at ${INFRA_ROOT}/.env"
  log_info "Terraform will use default AWS credentials."
fi

# Extract outputs (try both naming conventions)
API_GATEWAY_ID=$(terraform output -raw modular_api_gateway_id 2>/dev/null || terraform output -raw api_gateway_id 2>/dev/null || echo "")
API_GATEWAY_ENDPOINT=$(terraform output -raw modular_api_gateway_url 2>/dev/null || terraform output -raw api_gateway_endpoint 2>/dev/null || echo "")
AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")

if [[ -z "$API_GATEWAY_ID" ]]; then
  log_warn "API Gateway ID not found in Terraform outputs."
  log_info "Make sure your Terraform configuration has 'modular_api_gateway_id' or 'api_gateway_id' output."
  exit 1
fi

log_info "API Gateway ID: ${API_GATEWAY_ID}"
log_info "API Gateway Endpoint: ${API_GATEWAY_ENDPOINT}"

# --- Update validation .env file ---
if [[ -f "$VALIDATION_ENV" ]]; then
  log_step "Updating ${VALIDATION_ENV}..."
  
  # Update AWS_PROFILE
  if grep -q "^AWS_PROFILE=" "$VALIDATION_ENV"; then
    sed -i '' "s|^AWS_PROFILE=.*|AWS_PROFILE=${AWS_PROFILE}|" "$VALIDATION_ENV" 2>/dev/null || \
    sed -i "s|^AWS_PROFILE=.*|AWS_PROFILE=${AWS_PROFILE}|" "$VALIDATION_ENV"
  fi
  
  # Update API_GATEWAY_ID
  if grep -q "^API_GATEWAY_ID=" "$VALIDATION_ENV"; then
    sed -i '' "s|^API_GATEWAY_ID=.*|API_GATEWAY_ID=${API_GATEWAY_ID}|" "$VALIDATION_ENV" 2>/dev/null || \
    sed -i "s|^API_GATEWAY_ID=.*|API_GATEWAY_ID=${API_GATEWAY_ID}|" "$VALIDATION_ENV"
  fi
  
  # Update API_GATEWAY_ENDPOINT
  if grep -q "^API_GATEWAY_ENDPOINT=" "$VALIDATION_ENV"; then
    sed -i '' "s|^API_GATEWAY_ENDPOINT=.*|API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT}|" "$VALIDATION_ENV" 2>/dev/null || \
    sed -i "s|^API_GATEWAY_ENDPOINT=.*|API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT}|" "$VALIDATION_ENV"
  fi
  
  # Update AWS_REGION
  if grep -q "^AWS_REGION=" "$VALIDATION_ENV"; then
    sed -i '' "s|^AWS_REGION=.*|AWS_REGION=${AWS_REGION}|" "$VALIDATION_ENV" 2>/dev/null || \
    sed -i "s|^AWS_REGION=.*|AWS_REGION=${AWS_REGION}|" "$VALIDATION_ENV"
  fi
  
  log_info "Updated ${VALIDATION_ENV}"
else
  log_warn "Validation .env file not found: ${VALIDATION_ENV}"
  log_info "Creating new validation .env file..."
  
  mkdir -p "$(dirname "$VALIDATION_ENV")"
  cat > "$VALIDATION_ENV" << ENVEOF
# =============================================================================
# Validation Environment - Auto-generated from Terraform Outputs
# =============================================================================
# Generated by update-env-from-terraform.sh
# DO NOT COMMIT THIS FILE

# AWS Configuration (for API Gateway validation)
AWS_REGION=${AWS_REGION}
AWS_PROFILE=${AWS_PROFILE}
API_GATEWAY_ID=${API_GATEWAY_ID}
API_GATEWAY_ENDPOINT=${API_GATEWAY_ENDPOINT}

# Supabase Configuration (add manually if needed)
SUPABASE_URL=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_DB_HOST=
SUPABASE_DB_PORT=5432
SUPABASE_DB_NAME=postgres
SUPABASE_DB_USER=
SUPABASE_DB_PASSWORD=
ENVEOF
  
  log_info "Created ${VALIDATION_ENV}"
fi

# --- Update web app .env.local file ---
WEB_ENV="${STACK_DIR}/apps/web/.env.local"

if [[ -f "$WEB_ENV" ]]; then
  log_step "Updating ${WEB_ENV}..."
  
  # Remove trailing slash from endpoint if present
  CLEAN_ENDPOINT="${API_GATEWAY_ENDPOINT%/}"
  
  # Update NEXT_PUBLIC_CORA_API_URL
  if grep -q "^NEXT_PUBLIC_CORA_API_URL=" "$WEB_ENV"; then
    sed -i '' "s|^NEXT_PUBLIC_CORA_API_URL=.*|NEXT_PUBLIC_CORA_API_URL=\"${CLEAN_ENDPOINT}\"|" "$WEB_ENV" 2>/dev/null || \
    sed -i "s|^NEXT_PUBLIC_CORA_API_URL=.*|NEXT_PUBLIC_CORA_API_URL=\"${CLEAN_ENDPOINT}\"|" "$WEB_ENV"
    log_info "✅ Updated NEXT_PUBLIC_CORA_API_URL in ${WEB_ENV}"
  else
    echo "NEXT_PUBLIC_CORA_API_URL=\"${CLEAN_ENDPOINT}\"" >> "$WEB_ENV"
    log_info "✅ Added NEXT_PUBLIC_CORA_API_URL to ${WEB_ENV}"
  fi
else
  log_warn "Web app .env.local file not found: ${WEB_ENV}"
  log_info "Run the project creation script to generate .env files first."
fi

# --- Update setup.config.yaml (if exists) ---
if [[ -f "$CONFIG_FILE" ]]; then
  log_step "Updating ${CONFIG_FILE}..."
  
  # Check if yq is available
  if command -v yq &> /dev/null; then
    yq -i ".aws.api_gateway.id = \"${API_GATEWAY_ID}\"" "$CONFIG_FILE"
    yq -i ".aws.api_gateway.endpoint = \"${API_GATEWAY_ENDPOINT}\"" "$CONFIG_FILE"
    log_info "Updated API Gateway config in ${CONFIG_FILE}"
  else
    log_warn "yq not found. Please manually update ${CONFIG_FILE} with:"
    echo "  aws.api_gateway.id: \"${API_GATEWAY_ID}\""
    echo "  aws.api_gateway.endpoint: \"${API_GATEWAY_ENDPOINT}\""
  fi
fi

echo ""
log_info "✅ Environment files updated with Terraform outputs"
echo ""
log_info "You can now run the api-tracer validator:"
echo "  cd ${STACK_DIR}/scripts/validation/api-tracer"
echo "  python3 -m cli --path ${STACK_DIR}"
echo ""
