"""
Fix Proposer

Proposes fixes for schema validation errors.
Generates SQL migrations or code patches based on error type.
"""

import logging
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from difflib import SequenceMatcher

from validator import ValidationError

logger = logging.getLogger(__name__)


@dataclass
class ProposedFix:
    """Represents a proposed fix for a validation error."""
    error: ValidationError
    fix_type: str  # 'code_patch' or 'sql_migration'
    fix_content: str
    confidence: float  # 0.0 to 1.0
    rationale: str


class FixProposer:
    """Proposes fixes for schema validation errors."""
    
    def __init__(self):
        """Initialize fix proposer."""
        self.fixes: List[ProposedFix] = []
    
    def propose_fixes(self, errors: List[ValidationError]) -> List[ProposedFix]:
        """
        Propose fixes for validation errors.
        
        Args:
            errors: List of validation errors
            
        Returns:
            List of proposed fixes
        """
        self.fixes = []
        
        for error in errors:
            if error.severity != 'error':
                continue  # Only fix errors, not warnings
            
            fix = self._propose_fix_for_error(error)
            if fix:
                self.fixes.append(fix)
        
        logger.info(f"Generated {len(self.fixes)} proposed fixes")
        return self.fixes
    
    def _propose_fix_for_error(self, error: ValidationError) -> Optional[ProposedFix]:
        """
        Propose a fix for a single error.
        
        Args:
            error: Validation error
            
        Returns:
            ProposedFix or None if no fix can be proposed
        """
        # Missing table - propose SQL migration
        if error.table and error.column is None and "does not exist" in error.issue:
            return self._propose_table_creation(error)
        
        # Missing column - decide between code fix or migration
        if error.column and "does not exist" in error.issue:
            return self._propose_column_fix(error)
        
        return None
    
    def _propose_table_creation(self, error: ValidationError) -> ProposedFix:
        """
        Propose SQL migration to create missing table.
        
        Args:
            error: Validation error for missing table
            
        Returns:
            ProposedFix with SQL migration
        """
        sql = f"""-- Migration: Create table '{error.table}'
-- Generated by schema validator

CREATE TABLE IF NOT EXISTS {error.table} (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
    -- TODO: Add additional columns based on requirements
);

-- Add RLS policies as needed
ALTER TABLE {error.table} ENABLE ROW LEVEL SECURITY;
"""
        
        return ProposedFix(
            error=error,
            fix_type='sql_migration',
            fix_content=sql,
            confidence=0.5,  # Low confidence - requires manual review
            rationale="Table does not exist. Created basic table structure with id and timestamps."
        )
    
    def _propose_column_fix(self, error: ValidationError) -> ProposedFix:
        """
        Propose fix for missing column (code patch or migration).
        
        Args:
            error: Validation error for missing column
            
        Returns:
            ProposedFix with code patch or SQL migration
        """
        # Check if suggestion exists (likely a typo)
        if error.suggestion and "Did you mean" in error.suggestion:
            # Extract suggested column name
            suggested_col = self._extract_suggestion(error.suggestion)
            if suggested_col:
                return self._propose_code_patch(error, suggested_col)
        
        # No good suggestion - propose migration
        return self._propose_column_addition(error)
    
    def _propose_code_patch(self, error: ValidationError, correct_column: str) -> ProposedFix:
        """
        Propose code patch to fix column name typo.
        
        Args:
            error: Validation error
            correct_column: Correct column name
            
        Returns:
            ProposedFix with code patch
        """
        # Calculate confidence based on similarity
        similarity = SequenceMatcher(None, error.column, correct_column).ratio()
        
        # Generate unified diff-style patch
        patch = f"""--- {error.file}
+++ {error.file}
@@ Line {error.line} @@
-    # Uses column: '{error.column}'
+    # Uses column: '{correct_column}'

SUGGESTION: Replace '{error.column}' with '{correct_column}' in your code.
"""
        
        return ProposedFix(
            error=error,
            fix_type='code_patch',
            fix_content=patch,
            confidence=similarity,
            rationale=f"Column name '{error.column}' appears to be a typo. Correct name is '{correct_column}' (similarity: {similarity:.2f})"
        )
    
    def _propose_column_addition(self, error: ValidationError) -> ProposedFix:
        """
        Propose SQL migration to add missing column.
        
        Args:
            error: Validation error for missing column
            
        Returns:
            ProposedFix with SQL migration
        """
        sql = f"""-- Migration: Add column '{error.column}' to table '{error.table}'
-- Generated by schema validator

ALTER TABLE {error.table}
ADD COLUMN IF NOT EXISTS {error.column} TEXT;
-- TODO: Adjust data type, constraints, and default value as needed
"""
        
        return ProposedFix(
            error=error,
            fix_type='sql_migration',
            fix_content=sql,
            confidence=0.4,  # Low confidence - requires manual review
            rationale=f"Column '{error.column}' does not exist. Generated migration to add column with TEXT type (adjust as needed)."
        )
    
    def _extract_suggestion(self, suggestion_text: str) -> Optional[str]:
        """
        Extract suggested column name from suggestion text.
        
        Args:
            suggestion_text: Suggestion text like "Did you mean 'column_name'?"
            
        Returns:
            Extracted column name or None
        """
        import re
        match = re.search(r"'([^']+)'", suggestion_text)
        if match:
            return match.group(1)
        return None
    
    def prioritize_fixes(self) -> List[ProposedFix]:
        """
        Sort fixes by priority (code patches first, then migrations).
        High confidence fixes come first.
        
        Returns:
            Sorted list of fixes
        """
        # Sort by: 1) fix_type (code_patch first), 2) confidence (high first)
        return sorted(
            self.fixes,
            key=lambda f: (
                0 if f.fix_type == 'code_patch' else 1,  # Code patches first
                -f.confidence  # High confidence first
            )
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Export proposed fixes as dictionary (for JSON serialization).
        AI-friendly format for programmatic access.
        """
        prioritized = self.prioritize_fixes()
        
        return {
            'total_fixes': len(self.fixes),
            'code_patches': sum(1 for f in self.fixes if f.fix_type == 'code_patch'),
            'sql_migrations': sum(1 for f in self.fixes if f.fix_type == 'sql_migration'),
            'fixes': [
                {
                    'error': {
                        'file': f.error.file,
                        'line': f.error.line,
                        'table': f.error.table,
                        'column': f.error.column,
                        'issue': f.error.issue
                    },
                    'fix_type': f.fix_type,
                    'fix_content': f.fix_content,
                    'confidence': f.confidence,
                    'rationale': f.rationale
                }
                for f in prioritized
            ]
        }
